[local]
localhost ansible_host="127.0.0.1" ansible_connection="local" 



[web]
100.31.47.233


[local:vars]
NAME="Name from inventory file"

[web:vars]
ansible_user="ec2-user"
ansible_password="DevOps321"