[local]
localhost 

[mongodb]
mongodb-dev.rb.devarshi.live

[catalogue]
catalogue-dev.rb.devarshi.live

[redis]
redis-dev.rb.devarshi.live

[user]
user-dev.rb.devarshi.live

[cart]
cart-dev.rb.devarshi.live

[mysql]
mysql-dev.rb.devarshi.live

[shipping]
shipping-dev.rb.devarshi.live

[rabbitmq]
rabbitmq-dev.rb.devarshi.live

[payment]
payment-dev.rb.devarshi.live

[frontend]
frontend-dev.rb.devarshi.live

[dispatch]
dispatch-dev.rb.devarshi.live

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321
MONGODB_HOST=mongodb-dev.rb.devarshi.live
CATALOGUE_HOST=catalogue-dev.rb.devarshi.live
REDIS_HOST=redis-dev.rb.devarshi.live
USER_HOST=user-dev.rb.devarshi.live
CART_HOST=cart-dev.rb.devarshi.live
MYSQL_HOST=mysql-dev.rb.devarshi.live
SHIPPING_HOST=shipping-dev.rb.devarshi.live
RABBITMQ_HOST=rabbitmq-dev.rb.devarshi.live
PAYMENT_HOST=payment-dev.rb.devarshi.live
