- hosts: 127.0.0.1
  become: true
  vars: 
    var1: var-1 
    var2: var-2 
    var3: var-3
    common: &defaults
      project_name: "roboshop"
      version: "1.10"
      release: 2
    project_variables: 
      <<: *defaults
      timeout: 10s

    users: deva, rajesh, krishna, bala, rishi
    packages: nginx, curl, git
  tasks: 
    - name: run the disk info command 
      command: df -hT 
      register: disk_output
    - name: run the hello world command 
      command: echo "hello world from ansible"
      register: echo_output
    - debug: 
        msg: 
          split: "{{ users | split(',') }}"   
          join: "{{  users | split(',') | join('/') }}"
          project_varibles: "{{ project_variables }}" 