- name: variables-ansible
  hosts: local
  become: true
  vars: 
    # NAME: "NAME from playlevel variable"
    var2: variable-2
  
  tasks: 
    - name: Print Name - Varaible precedence in ansible
      vars:
        var_1: var1 from the print_named debug task 
      ansible.builtin.debug: 
        msg:  
          name: "{{ NAME }}"
    - name: debug-2 
      vars:
        var_2: vasr2 from debug-2 task
      debug: 
        msg: 
          ansile_facts: "{{ansible_facts}}"
          

#1. command argument level 
#2. task level variable 
#3. file level varaibles
#4. prompt level
#5. Play level varibles
#6. inventory level
