- name: pay-1
  hosts: local 
  become: true
  vars: 
    var1: variable-1
    var2: variable-2
    var3: variable-3
    var4: variable-4
    var5: variable-5
    users: 
      - deva 
      - rajesh 
      - krishna
      - bala
    # packages: ["nginx", "curl", "git", "zip", "redis"]
    packages: 
      - name: nginx
        state: absent
      - name: curl
        state: present
      - name: git
        state: present
      - name: zip
        state: present
      - name: redis
        state: absent

  vars_files:
    - vars/var_file_1.yaml
  

  tasks: 
    - name: print_names
      debug: 
        msg: 
          message: "Hi here {{ item }}"
          packages: "{{ packages | to_nice_json(indent=4) }}"
        
      loop: "{{ users  }}"
    
    - name: copy 
      copy: 
        content: "{{packages | to_nice_json(indent=4)}}"
        dest: "/workspaces/codespaces-blank/ansible-simple/output.json"
      delegate_to: localhost

    # - name: install packages
    #   ansible.builtin.package: 
    #     name: "{{ item.name }}"
    #     state: "{{ item.state }}"
    #   loop: "{{ packages }}"

    - name: item2dict
      vars: 
        Tags: [
          {key: Name, value: Devarshi_Balu},
          {key: Age, value: 20}
        ]
      debug: 
        msg: 
          tags: "{{ Tags | items2dict }}"
          