- name: play-1
  hosts: local
  connection: local
  vars:
    var_1: var-2
    users: 
      - deva 
      - rajesh 
      - krishna
      - bala
    packages: nginx, curl, git, zip, redis  
 
  vars_files: 
    - vars/var_file_1.yaml
  
  tasks: 
    - name: print_os_family
      ansible.builtin.debug: 
        msg: 
          os_family: "os_family={{ ansible_facts.os_family }}"
    
    - name: set_facts to the ansible facts    
      ansible.builtin.copy:
        content: "{{ lookup('file', '05-items.yaml') | from_yaml | to_nice_json(indent=2) }}"
        dest: "/workspaces/codespaces-blank/ansible-simple/output.json"
      delegate_to: localhost

    - name: set_facts to the ansible facts    
      ansible.builtin.set_fact:
        student_yaml: "{{ lookup('file', '07-items.yaml') | from_yaml | to_nice_json(indent=2) }}"
  
    - name: print_file content
      ansible.builtin.debug: 
        msg: 
          file_content: "{{ student_yaml | to_nice_json(indent=4) }}"

    - name: debug the host vars
      debug: 
        var: hostvars
      
    - name: filters with arrays 
      debug: 
        msg:
          join: "{{ users | join('/') }}" 
          split: "{{ packages | split(',') }}" 
    
    - name: install the packages
      debug: 
        msg: "{{ item }}"
      loop: "{{packages | split(',')}}"

      


          
