- name: play-1
  hosts: local
  become: true
  connection: local
  vars:
    var_1: var-2
    users: 
      - deva 
      - rajesh 
      - krishna
      - bala
    becomes: yes
    packages: nginx, curl, git, zip, redis  
 
  vars_files: 
    - vars/var_file_1.yaml
  
  tasks:  
    - name: check user exists or not  
      command: id roboshop
      register: user_output
      ignore_errors: true

    - name: print the user output
      debug:  
        msg: 
          user_output: "{{user_output}}"
          becomes: "{{ becomes }}"

    - name: add the user if user doesnt exist
      command: useradd --system -m -d /app --comment "roboshop system user" --shell /sbin/nologin roboshop
      register: user_add_2_output
      when: (user_output.rc != 0)
