- name: play-1
  hosts: local
  vars: 
    students:
      - name: Ravi
        branch: CSE

      - name: Priya
        branch: ECE

      - name: Arjun
        branch: CSE

  tasks:
    - name: select functions on the dictionaries
      ansible.builtin.debug: 
        msg: 
          cse: "{{ students | selectattr('branch', 'equalto', 'CSE') }}"
          no_ece: "{{ students | rejectattr('branch', 'equalto', 'ECE') }}"

